//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marmeladka.core.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_order
    {
        public System.Guid id { get; set; }
        public System.Guid productId { get; set; }
        public System.Guid ordersId { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
